// conhecendo_outro_framework/root/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent {

}

<main class="container">
  <br />
  <h1>Catálogo de Livros</h1>
  <table class="table table-striped">
    <thead class="table-dark text-white">
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Autores</th>
        <th>Editora</th>
        <th>Opções</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>{{ livro.titulo }}</td>
        <td>{{ livro.resumo }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <button class="btn btn-danger" (click)="excluir(livro.codigo)">
            Excluir
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// framework_acessando_bd/clientes/livros-next/pages/LivroLista.tsx
import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { Menu } from '../componentes/Menu';
import styles from '../styles/Home.module.css';
import ControleLivros from '../classes/controle/ControleLivros';

interface Livro {
  codigo: string;
  titulo: string;
  autor: string;
  ano: number;
}

const LivroLista: React.FC = () => {
  const controleLivros = new ControleLivros();
  const [livros, setLivros] = useState<Array<Livro>>([]);
  const [carregado, setCarregado] = useState<boolean>(false);

  useEffect(() => {
    if (!carregado) {
      controleLivros.obterLivros().then((dados) => {
        setLivros(dados);
        setCarregado(true);
      });
    }
  }, [carregado]);

  const excluir = async (codigo: string) => {
    controleLivros.excluirLivro(codigo).then((sucesso) => {
      if (sucesso) {
        setCarregado(false);
      }
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Lista de Livros</title>
      </Head>
      <Menu />
      <main>
        <h1>Lista de Livros</h1>
        <table className="table">
          <thead>
            <tr>
              <th>Código</th>
              <th>Título</th>
              <th>Autor</th>
              <th>Ano</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <tr key={index}>
                <td>{livro.codigo}</td>
                <td>{livro.titulo}</td>
                <td>{livro.autor}</td>
                <td>{livro.ano}</td>
                <td>
                  <button onClick={() => excluir(livro.codigo)}>Excluir</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;
