// framework_acessando_bd/clientes/livros-react/src/LivroDados.js
// Importações
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleLivro from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

// Definição do componente
export default function LivroDados() { 
    const controleLivro = new ControleLivro();
    const controleEditora = new ControleEditora();

    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }));

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);

    
    const navigate = useNavigate();

    
    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value)); 
    };

    const incluir = (event) => {
        event.preventDefault();

        
        const novoLivro = {
            codigo: 0,
            titulo: titulo,
            resumo: resumo,
            autores: autores.split('\n'), 
            codEditora: codEditora
        };

        
        controleLivro.incluirLivro(novoLivro);

        navigate('/');
    };

    return (
        <main>
            <h2>Dados do livro</h2>
            <form onSubmit={incluir}>
                <div className="form-group">
                    <label htmlFor="titulo">Título</label>
                    <input type="text" id="titulo" className="form-control" value={titulo} onChange={(e) => setTitulo(e.target.value)} required/>
                </div>
                <div className="form-group">
                    <label htmlFor="resumo">Resumo</label>
                    <textarea id="resumo" maxLength={400} className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} required/>
                </div>
                <div className="form-group">
                    <label htmlFor="editora">Editora</label>
                    <select id="editora" className="form-control" value={codEditora} onChange={tratarCombo} required>
                        {opcoes.map(opcao => (
                            <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                        ))}
                    </select>
                </div>
                <div className="form-group">
                    <label htmlFor="autores">Autores (1 por linha)</label>
                    <textarea id="autores" className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} required/>
                </div>
                
                <button type="submit" className="btn btn-primary mt-2">Salvar dados</button>
            </form>
        </main>
    );
}

// framework_acessando_bd/root/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core'
import { Router } from '@angular/router'
import { ControleEditoraService } from '../controle/controle-editora.service'
import { ControleLivrosService } from '../controle/controle-livros.service'
import { Editora } from '../editora'
import { Livro } from '../livro'



// Inicializando o Componente
@Component({
  selector: "app-livro-dados",
  templateUrl: "./livro-dados.component.html",
  styleUrls: ["./livro-dados.component.css"]
})
export class LivroDadosComponent implements OnInit {
  livro: Livro
  autoresForm: string = ""
  editoras: Array<Editora> = []

  // Construtor com injeção de dependencias, e Serviços de controle
  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {

    // Instanciando o livro
    this.livro = new Livro(1, 1, "", '', [])
  }

  // Funções
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras()
  }

  incluir(): void {
    this.livro.autores = this.autoresForm.split("\n")
    this.servLivros.incluir(this.livro)
    this.router.navigateByUrl("/lista")
  }

  cancelar(): void {
    this.router.navigateByUrl("/lista")
  }
}

<main class="container">
  <h1>Dados do Livro</h1>
  <form (ngSubmit)="incluir()" #livroForm="ngForm">



    <div class="form-group">
      <abbr title="Os itens marcados (*) são obrigatórios"><label for="titulo">Título*</label></abbr>
      <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo" required />
    </div>
    <div class="form-group">
      <abbr title="Os itens marcados (*) são obrigatórios"><label for="resumo">Resumo*</label></abbr>
      <textarea class="form-control" id="resumo" rows="3" [(ngModel)]="livro.resumo" name="resumo" required></textarea>
    </div>
    <div class="form-group">
      <abbr title="Os itens marcados (*) são obrigatórios"><label for="editora">Editora*</label></abbr>
      <select class="form-control" id="editora" required [(ngModel)]="livro.codEditora" name="editora">
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>
    <div class="form-group">
      <abbr title="Os itens marcados (*) são obrigatórios"><label for="autores">Autores* (1 Por linha)</label></abbr>
      <textarea class="form-control" id="autores" rows="3" [(ngModel)]="autoresForm" name="autores"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar Dados</button>
    <button type="button" class="btn btn-secondary m-3" (click)="cancelar()">
      Cancelar
    </button>
  </form>
</main>
